# LoRA from Scratch

### Notebook to help understand how LoRA works.

In [1]:
import torch
import numpy as np
torch.manual_seed(1)

In [2]:
d, k = 10, 10

rank = 2
W = torch.randn(d,rank) @ torch.randn(rank,k)
print(W)

tensor([[-0.4902,  1.2622, -1.0716,  0.5020, -0.4107,  1.2846,  2.4297,  0.8886,
          0.6491, -2.9506],
        [-0.5303,  2.8276, -1.8984, -0.1688, -0.3176,  1.3831,  0.4896, -1.5201,
          2.5795, -3.3387],
        [ 0.2331, -0.3944,  0.4055, -0.3389,  0.2131, -0.6118, -1.4564, -0.7718,
         -0.0443,  1.3823],
        [ 0.0687, -1.4636,  0.8006,  0.5560, -0.0539, -0.1743,  1.5414,  2.0590,
         -1.7430,  0.5429],
        [ 0.3786, -2.0593,  1.3758,  0.1403,  0.2232, -0.9872, -0.2900,  1.1542,
         -1.8937,  2.3876],
        [ 0.3281,  0.2501,  0.1638, -0.8692,  0.3698, -0.8648, -3.2282, -2.4531,
          0.9715,  1.8651],
        [-0.1414,  1.0995, -0.6809, -0.2133, -0.0547,  0.3672, -0.3750, -0.9918,
          1.1315, -0.9249],
        [-0.1916,  0.1972, -0.2691,  0.3404, -0.1862,  0.5034,  1.3828,  0.8498,
         -0.1265, -1.1235],
        [-0.0755, -0.6325,  0.2530,  0.4799, -0.1349,  0.2015,  1.5838,  1.5402,
         -0.9618, -0.3713],
        [ 0.4815, -

Recall that SVD is defined as the following: $$ W = U \Sigma V^{T}$$ where $W$ is an $m x n$ matrix, $U$ is an $m x m$ matrix, $\Sigma$ is an $m x n$ matrix and $V^{T}$ is an $n x n$ matrix.

In [3]:
U, S, V = torch.svd(W)

U_r = U[:, :rank]
S_r = torch.diag(S[:rank])
V_r = V[:, :rank].t()

In the LoRA paper, recall that we created matrices A (r x k) and B (d x r). We can create these matrices using the rank factorized matrices from the SVD we performed.

In [4]:
A = V_r
B = U_r @ S_r

print(f"A shape: {A.shape}")
print(f"B shape: {B.shape}")


A shape: torch.Size([2, 10])
B shape: torch.Size([10, 2])


We can test how accurate BA is by comparing how similar the results are when providing input to W and BA.

In [19]:
x = torch.randn(d)

# y = Wx
y = W @ x
# y' = (B*A)x
y_prime = (B @ A) @ x

print("Original y using W:\n", y)
print("")
print("y' computed using BA:\n", y_prime)

print("Total parameters of W: ", W.nelement())
print("Total parameters of B and A: ", B.nelement() + A.nelement())

Original y using W:
 tensor([-6.3192, -4.3742,  3.3514, -1.2804,  3.0542,  6.0737, -0.5844, -2.9684,
        -2.3654,  3.1847])

y' computed using BA:
 tensor([-6.3192, -4.3742,  3.3514, -1.2804,  3.0542,  6.0737, -0.5844, -2.9684,
        -2.3654,  3.1847])
Total parameters of W:  100
Total parameters of B and A:  40


This is the basis of why LoRA is such a powerful technique. We were able to replicate the original matrix's behavior with far fewer parameters. This is why LoRA is significantly more memory efficient than other techniques that were created for the purpose of fine-tuning models.

# LoRA in application

Let's apply LoRA to a simple neural network

In [136]:
import torch.nn.functional as F
import torch.optim as optim
import torch.nn.utils.parametrize as parametrize
from torch import nn
from torchvision import datasets, transforms
from tqdm import tqdm

In [137]:
# Download MNIST
transform = transforms.Compose([transforms.ToTensor()])

# Download and load the training data
trainset = datasets.MNIST(root='../data', train=True, download=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=64, shuffle=True)

# Download and load the test data
testset = datasets.MNIST(root='../data', train=False, download=True, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=64, shuffle=False)

images, labels = next(iter(trainloader))

print(f"Image batch shape: {images.shape}")
print(f"Label batch shape: {labels.shape}")

Image batch shape: torch.Size([64, 1, 28, 28])
Label batch shape: torch.Size([64])


Simple CNN with three convolution layers.

In [138]:
class ConvNetwork(nn.Module):
    def __init__(self, input_channels):
        super(ConvNetwork, self).__init__()
        self.conv1 = nn.Conv2d(input_channels, 32, kernel_size=3, stride=2, padding=1)
        self.conv2 = nn.Conv2d(32, 64, kernel_size=3, stride=2, padding=1)
        self.conv3 = nn.Conv2d(64, 128, kernel_size=3, stride=2, padding=1)
        self.flatten = nn.Flatten()
        self.fc = nn.Linear(128 * 4 * 4, 10)
        
    
    def forward(self, x):
        x = F.relu(self.conv1(x))
        x = F.relu(self.conv2(x))
        x = F.relu(self.conv3(x))
        x = self.flatten(x)
        x = self.fc(x)
        
        return x

In [139]:
net = ConvNetwork(input_channels=1)

optimizer = optim.Adam(net.parameters(), lr=0.001)
criterion = nn.CrossEntropyLoss()

def train(train_loader, net, epochs=5, total_iterations_limit=None):
    cross_el = nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(net.parameters(), lr=0.001)

    total_iterations = 0

    for epoch in range(epochs):
        net.train()

        loss_sum = 0
        num_iterations = 0

        data_iterator = tqdm(train_loader, desc=f'Epoch {epoch+1}')
        if total_iterations_limit is not None:
            data_iterator.total = total_iterations_limit
        for data in data_iterator:
            num_iterations += 1
            total_iterations += 1
            x, y = data
            x = x
            y = y
            optimizer.zero_grad()
            output = net(x.view(-1, 1, 28, 28))
            loss = cross_el(output, y)
            loss_sum += loss.item()
            avg_loss = loss_sum / num_iterations
            data_iterator.set_postfix(loss=avg_loss)
            loss.backward()
            optimizer.step()

            if total_iterations_limit is not None and total_iterations >= total_iterations_limit:
                return

train(trainloader, net, epochs=1)

Epoch 1: 100%|██████████| 938/938 [00:28<00:00, 32.67it/s, loss=0.223]


Let's consider this to be our "pre-trained" weights. We can then apply LoRA on these original weights by fine tuning on a specific number.

In [140]:
original_weights = {}
for name, param in net.named_parameters():
    original_weights[name] = param.clone().detach()

print(f'Weights shape: {len(original_weights)}')

total_parameters_original = 0
for index, layer in enumerate([net.conv1, net.conv2, net.conv3, net.fc]):
    total_parameters_original += layer.weight.nelement() + layer.bias.nelement()
    print(f'Layer {index+1}: W: {layer.weight.shape} + B: {layer.bias.shape}')
print(f'Total number of parameters: {total_parameters_original:,}')

Weights shape: 8
Layer 1: W: torch.Size([32, 1, 3, 3]) + B: torch.Size([32])
Layer 2: W: torch.Size([64, 32, 3, 3]) + B: torch.Size([64])
Layer 3: W: torch.Size([128, 64, 3, 3]) + B: torch.Size([128])
Layer 4: W: torch.Size([10, 2048]) + B: torch.Size([10])
Total number of parameters: 113,162


In [141]:
def test():
    correct = 0
    total = 0

    wrong_counts = [0 for i in range(10)]

    with torch.no_grad():
        for data in tqdm(testloader, desc='Testing'):
            x, y = data
            x = x
            y = y
            output = net(x.view(-1, 1, 28, 28))
            for idx, i in enumerate(output):
                if torch.argmax(i) == y[idx]:
                    correct +=1
                else:
                    wrong_counts[y[idx]] +=1
                total +=1
    print(f'Accuracy: {round(correct/total, 3)}')
    for i in range(len(wrong_counts)):
        print(f'wrong counts for the digit {i}: {wrong_counts[i]}')

test()

Testing: 100%|██████████| 157/157 [00:03<00:00, 51.40it/s]

Accuracy: 0.978
wrong counts for the digit 0: 7
wrong counts for the digit 1: 10
wrong counts for the digit 2: 14
wrong counts for the digit 3: 21
wrong counts for the digit 4: 16
wrong counts for the digit 5: 6
wrong counts for the digit 6: 15
wrong counts for the digit 7: 36
wrong counts for the digit 8: 55
wrong counts for the digit 9: 36


Since there is high number of wrong counts for the number 3, let's fine tune our model on 3. First, we will have to implement LoRA which we can apply to each layer using parametrizations. This implementation follows the original LoRA paper (Hu et. al.). Similar to the paper, I am only applying LoRA to the weight matrix of the convolution layers (excluding the bias). 

In [142]:
class LoRA(nn.Module):
    def __init__(self, features_in, features_out, rank=1, alpha=1):
        super(LoRA, self).__init__()
        # A (r x k)
        self.lora_A = nn.Parameter(torch.zeros((rank,features_out)))
        # B (d x r)
        self.lora_B = nn.Parameter(torch.zeros((features_in, rank)))
        # Section 4.1 states that A is initialized to a random gaussian distribution while B is intialized to 0. Thus initially, ∆W = BA = 0.
        nn.init.normal_(self.lora_A, mean=0, std=1)
        self.scale = alpha / rank
        self.enabled = True

    def forward(self, original_weights):
        if self.enabled:
            # W + BA * scale
            return original_weights + torch.matmul(self.lora_B, self.lora_A).view(original_weights.shape) * self.scale
        else:
            return original_weights

def conv_layer_parameterization(layer, rank=1, alpha=1):
    out_channels, in_channels, kernel_height, kernel_width = layer.weight.shape
    features_in = in_channels * kernel_height * kernel_width
    features_out = out_channels
    return LoRA(features_in, features_out, rank=rank, alpha=alpha)

def linear_layer_parameterization(layer, rank=1, alpha=1):
    features_in, features_out = layer.weight.shape
    return LoRA(features_in, features_out, rank, alpha)

parametrize.register_parametrization(
    net.conv1, "weight", conv_layer_parameterization(net.conv1)
)
parametrize.register_parametrization(
    net.conv2, "weight", conv_layer_parameterization(net.conv2)
)
parametrize.register_parametrization(
    net.conv3, "weight", conv_layer_parameterization(net.conv3)
)

parametrize.register_parametrization(
    net.fc, "weight", linear_layer_parameterization(net.fc)
)

def enable_disable_lora(enabled=True):
    for layer in [net.conv1, net.conv2, net.conv3, net.fc]:
        layer.parametrizations["weight"][0].enabled = enabled

In [143]:
total_parameters_lora = 0
total_parameters_non_lora = 0
for index, layer in enumerate([net.conv1, net.conv2, net.conv3, net.fc]):
    total_parameters_lora += layer.parametrizations["weight"][0].lora_A.nelement() + layer.parametrizations["weight"][0].lora_B.nelement()
    total_parameters_non_lora += layer.weight.nelement() + layer.bias.nelement()
    print(
        f'Layer {index+1}: W: {layer.weight.shape} + B: {layer.bias.shape} + Lora_A: {layer.parametrizations["weight"][0].lora_A.shape} + Lora_B: {layer.parametrizations["weight"][0].lora_B.shape}'
    )

assert total_parameters_non_lora == total_parameters_original

print(f'Total number of parameters (original): {total_parameters_non_lora:,}')
print(f'Total number of parameters (original + LoRA): {total_parameters_lora + total_parameters_non_lora:,}')
print(f'Parameters introduced by LoRA: {total_parameters_lora:,}')
parameters_increment = (total_parameters_lora / total_parameters_non_lora) * 100
print(f'Parameters increment: {parameters_increment:.3f}%')

Layer 1: W: torch.Size([32, 1, 3, 3]) + B: torch.Size([32]) + Lora_A: torch.Size([1, 32]) + Lora_B: torch.Size([9, 1])
Layer 2: W: torch.Size([64, 32, 3, 3]) + B: torch.Size([64]) + Lora_A: torch.Size([1, 64]) + Lora_B: torch.Size([288, 1])
Layer 3: W: torch.Size([128, 64, 3, 3]) + B: torch.Size([128]) + Lora_A: torch.Size([1, 128]) + Lora_B: torch.Size([576, 1])
Layer 4: W: torch.Size([10, 2048]) + B: torch.Size([10]) + Lora_A: torch.Size([1, 2048]) + Lora_B: torch.Size([10, 1])
Total number of parameters (original): 113,162
Total number of parameters (original + LoRA): 116,317
Parameters introduced by LoRA: 3,155
Parameters increment: 2.788%


If we did not have LoRA, we would have had double the number of parameters as the original as we would have needed a new weight value for each parameter. However, with this approach, we are only adding in a marginal fraction of the original number of parameters, 1.184% to be exact.

Now, we can fine-tune our model by training specifically on the data with label = 9.

In [150]:
# Freeze the non-LoRA parameters
for name, param in net.named_parameters():
    if 'lora' not in name:
        print(f'Freezing non-LoRA parameter {name}')
        param.requires_grad = False

trainset = datasets.MNIST(root='../data', train=True, download=True, transform=transform)

label_9_indices = trainset.targets == 9
label_9_data = trainset.data[label_9_indices]
label_9_targets = trainset.targets[label_9_indices]

trainloader = torch.utils.data.DataLoader(trainset, batch_size=10, shuffle=True)

train(trainloader, net, epochs=1, total_iterations_limit=150)

Freezing non-LoRA parameter conv1.bias
Freezing non-LoRA parameter conv1.parametrizations.weight.original
Freezing non-LoRA parameter conv2.bias
Freezing non-LoRA parameter conv2.parametrizations.weight.original
Freezing non-LoRA parameter conv3.bias
Freezing non-LoRA parameter conv3.parametrizations.weight.original
Freezing non-LoRA parameter fc.bias
Freezing non-LoRA parameter fc.parametrizations.weight.original


Epoch 1:  99%|█████████▉| 149/150 [00:00<00:00, 252.23it/s, loss=0.0767]


In [151]:
assert torch.all(net.conv1.parametrizations.weight.original == original_weights['conv1.weight'])
assert torch.all(net.conv2.parametrizations.weight.original == original_weights['conv2.weight'])
assert torch.all(net.conv3.parametrizations.weight.original == original_weights['conv3.weight'])

In [152]:
def print_layer_weights(layer, name):
    print(f"--- {name} Weights ---")
    print(layer.weight)
    if "weight" in layer.parametrizations:
        print(f"--- {name} LoRA A Weights ---")
        print(layer.parametrizations["weight"][0].lora_A)
        print(f"--- {name} LoRA B Weights ---")
        print(layer.parametrizations["weight"][0].lora_B)
    print("\n")


print_layer_weights(net.conv1, "Conv2")
enable_disable_lora(True)
print_layer_weights(net.conv1, "Conv2 with LoRA Enabled")
enable_disable_lora(False)
print_layer_weights(net.conv1, "Conv2 with LoRA Disabled")

--- Conv2 Weights ---
tensor([[[[ 5.4542e-02, -1.1004e-01, -7.2091e-02],
          [ 3.0230e-01,  4.0325e-01,  2.7085e-01],
          [ 9.7088e-02,  6.1541e-02,  8.7011e-02]]],


        [[[-5.9163e-02,  5.7745e-02,  2.9829e-01],
          [ 3.3142e-02,  3.8169e-01, -1.2669e-01],
          [ 3.4723e-01, -1.0002e-01, -1.0380e-01]]],


        [[[ 5.1117e-02,  2.9254e-01,  1.3561e-01],
          [ 1.4960e-01,  5.5135e-02,  1.1491e-01],
          [ 3.5642e-01, -1.4782e-01, -1.0589e-01]]],


        [[[-3.1451e-02, -1.5944e-01, -1.0673e-01],
          [-2.7437e-01, -3.5646e-01, -1.3678e-01],
          [-2.3790e-01,  6.7900e-02,  1.5416e-01]]],


        [[[ 1.9741e-01,  2.9132e-01, -9.4598e-02],
          [-3.5829e-01,  9.5019e-02,  1.4182e-01],
          [-2.1460e-02,  4.7081e-02,  2.9024e-01]]],


        [[[ 4.0013e-01,  2.8954e-02,  1.0780e-01],
          [ 1.7661e-01, -1.8618e-01,  2.1708e-01],
          [-2.1661e-01, -1.2673e-01, -2.0302e-01]]],


        [[[ 9.5009e-02,  1.5142e-01,

We can now test our fine-tuned network:

In [153]:
enable_disable_lora(enabled=True)
test()

Testing: 100%|██████████| 157/157 [00:03<00:00, 50.28it/s]

Accuracy: 0.982
wrong counts for the digit 0: 6
wrong counts for the digit 1: 9
wrong counts for the digit 2: 17
wrong counts for the digit 3: 19
wrong counts for the digit 4: 24
wrong counts for the digit 5: 10
wrong counts for the digit 6: 14
wrong counts for the digit 7: 30
wrong counts for the digit 8: 24
wrong counts for the digit 9: 31


In [148]:
enable_disable_lora(enabled=False)
test()

Testing: 100%|██████████| 157/157 [00:03<00:00, 48.87it/s]

Accuracy: 0.978
wrong counts for the digit 0: 7
wrong counts for the digit 1: 10
wrong counts for the digit 2: 14
wrong counts for the digit 3: 21
wrong counts for the digit 4: 16
wrong counts for the digit 5: 6
wrong counts for the digit 6: 15
wrong counts for the digit 7: 36
wrong counts for the digit 8: 55
wrong counts for the digit 9: 36
